version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "python_app/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r python_app/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "python_app/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 python_app/tests.py
      - store_artifacts:
          path: test-reports/
          destination: python_app