version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "python_app/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r python_app/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "python_app/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 python_app/tests.py
      - store_artifacts:
          path: test-reports/
          destination: python_app
steps:
  - add_ssh_keys:
      fingerprints:
        - "2048 SHA256:2Ur87hZNYwot6XVwf97ATkYEmLkkFhwDOBGxt260y/E root@ip-172-31-51-19 (RSA)"
    - run: ssh -i "key-pair-pem-file.pem" ubuntu@ec2-54-162-47-105.compute-1.amazonaws.com python_app/test.sh
   
